name: Push ruby gems

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  push-ruby-gems:
    name: "Push ruby gems"
    runs-on: ${{ github.repository_owner == 'grafana' && 'ubuntu-x64-small' || 'ubuntu-latest' }}
    if: "startsWith(github.event.release.tag_name, 'ruby-')"
    steps:
      - uses: rubygems/configure-rubygems-credentials@bc6dd217f8a4f919d6835fcfefd470ef821f5c44 # v1.0.0
      - uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # 1.12
        with:
          tag: ${{ github.event.release.tag_name }}
          fileName: "*"
          tarBall: false
          zipBall: false
          out-file-path: "dist"
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ruby/setup-ruby@0cb964fd540e0a24c900370abf38a33466142735 # v1.305.0 # trufflehog:ignore
        with:
          ruby-version: '4.0.2'
      - run: |
          set -ex
          cd dist
          ls
          for gem in *.gem;
          do
            gem push "${gem}";
            sleep 5;
          done
